<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>flink-cdc-demo-1-20</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>Flink CDC Demo</name>
    <description>Flink CDC Examples with Java 11 and Flink 1.20.3</description>

    <properties>
        <java.version>11</java.version>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <flink.version>1.20.4</flink.version>
        <flink.cdc.version>3.6.0-1.20</flink.cdc.version>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.encoding>UTF-8</maven.compiler.encoding>
    </properties>

    <dependencies>
        <!--基础 API 层（批处理环境）：批处理（Batch）API，即 ExecutionEnvironment-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-java</artifactId>
            <version>${flink.version}</version>
            <scope>${flink.scope}</scope>
        </dependency>

        <!--流处理核心引擎（DataStream API）：流处理（Streaming）API，即 StreamExecutionEnvironment-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java</artifactId>
            <version>${flink.version}</version>
            <scope>${flink.scope}</scope>
        </dependency>

        <!--提交客户端（Client）：在 IDE 中本地运行 Flink 程序（必须）。
        虽然没有显式调用 flink-clients，但 StreamExecutionEnvironment.execute() 内部会使用它来启动本地执行环境。-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-clients</artifactId>
            <version>${flink.version}</version>
            <scope>${flink.scope}</scope>
        </dependency>

        <!--日志-->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.25.4</version>
            <scope>${flink.scope}</scope>
        </dependency>

        <!--web ui-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-runtime-web</artifactId>
            <version>${flink.version}</version>
            <scope>${flink.scope}</scope>
        </dependency>

        <!--连接 Table API/SQL 和 DataStream API 的桥梁
        流与表的相互转换，本地 IDE 开发与调试（必须显式添加）-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-api-java-bridge</artifactId>
            <version>${flink.version}</version>
            <scope>${flink.scope}</scope>
        </dependency>
        <!--所有 Table API/SQL 作业的运行基础（必需）
        Flink Table API 和 SQL 的核心计划器（Planner）模块。
        它负责将开发者编写的 SQL 或 Table API 代码，翻译、优化并最终转换成 Flink 运行时可以执行的物理任务。
        本地 IDE 开发与调试（必须显式添加）-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-planner-loader</artifactId>
            <version>${flink.version}</version>
            <scope>${flink.scope}</scope>
        </dependency>

        <!--Flink Table API 和 SQL 的核心运行时引擎。
        简单来说，它负责把你写的 SQL 或 Table API 代码真正“跑”起来。-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-runtime</artifactId>
            <version>${flink.version}</version>
            <scope>${flink.scope}</scope>
        </dependency>


        <!--下面是connector
        通常使用默认的 compile 或不写 scope 确保依赖被打进最终的作业 JAR 包中。
        因为 Flink 集群的 lib 目录下默认不包含这些连接器-->

        <!--监听并捕获 MySQL 等数据库的实时变更（增、删、改）-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-mysql-cdc</artifactId>
            <version>${flink.cdc.version}</version>
        </dependency>

        <!--文件读取、写入-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-files</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <!--kafka connector-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-kafka</artifactId>
            <version>3.4.0-1.20</version>
        </dependency>

        <!--以jdbc方式读取、写入数据库-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-jdbc</artifactId>
            <version>3.3.0-1.20</version>
        </dependency>

        <!--开发测试用的数据生成器-->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-datagen</artifactId>
            <version>1.20.3</version>
        </dependency>

        <!-- 注意：此处 <jackson-databind> + <flink-connector-kafka> 会导致冲突！ -->
        <!-- Mysql CDC source 的json 解析 JsonDebeziumDeserializationSchema 静默卡死。-->
        <!-- <dependency>-->
        <!--     <groupId>com.fasterxml.jackson.core</groupId>-->
        <!--     <artifactId>jackson-databind</artifactId>-->
        <!--     <version>2.21.2</version>-->
        <!-- </dependency>-->
    </dependencies>

    <profiles>
        <profile>
            <id>local</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <flink.scope>compile</flink.scope>
            </properties>
        </profile>
        <profile>
            <id>cluster</id>
            <properties>
                <flink.scope>provided</flink.scope>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <!-- Java 版本 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>

            <!-- 打包插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


</project>